site_name: OpenSky Converter

theme:
  name: material
  features:
    - navigation.footer

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Flowcharts:
    - Main Window: main_window.md
    - Mapping Dialog: mapping_dialog.md
    - Conversion Process: conversion_process.md
    - Reset to Defaults Dialog: reset_to_defaults.md
  - Reference:
    - Main Window: reference/main_window.md
    - Mapping Dialog: reference/mapping_dialog.md
