site_name: Aircraft DB Converter

site_url: ""

use_directory_urls: false

theme:
  name: material
  features:
    - navigation.footer

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Main Window: guide/main_window.md
    - Mapping Dialog: guide/mapping_dialog.md
    - Progress Dialog: guide/progress_dialog.md
    - Reset to Defaults Dialog: guide/reset_to_defaults_dialog.md
  - Flowcharts:
    - Main Window: flowcharts/main_window.md
    - Mapping Dialog: flowcharts/mapping_dialog.md
    - Conversion Process: flowcharts/conversion_process.md
    - Reset to Defaults Dialog: flowcharts/reset_to_defaults.md
  - Reference:
    - Main Window: reference/main_window.md
    - Mapping Dialog: reference/mapping_dialog.md
    - Progress Dialog: reference/progress_dialog.md
    - Reset to Defaults Dialog: reference/reset_to_defaults_dialog.md
    - Converter: reference/converter.md
